# Generated by Django 4.2 on 2023-07-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=70)),
                ('destination', models.CharField(max_length=70)),
                ('expected_delivery_date', models.DateTimeField()),
                ('actual_delivery_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('packing', 'packing'), ('arrived_at', 'arrivedat'), ('dispatched_from', 'dispatched_from'), ('delivered', 'delivered')], max_length=70)),
                ('location', models.CharField(max_length=70)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.shipment')),
            ],
        ),
    ]
