# Generated by Django 4.2 on 2023-07-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('early', 'early'), ('delayed', 'delayed'), ('on-time', 'on-time')], max_length=20),
        ),
    ]
