# Generated by Django 4.2 on 2023-07-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('account_type', models.CharField(choices=[('saving_account', 'saving_account'), ('current_account', 'current_account')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addres', models.TextField(verbose_name=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('accounts', models.ManyToManyField(to='banking.account')),
            ],
        ),
    ]
